### ISSUE TITLE
add admin port to InstanceMetadata and publish in CuratorAdvertiser

### ISSUE THREAD

**Issue by stantonk** [dropwizard/dropwizard-discovery#10]
In distributed environments, being able to allocate ports dynamically (via setting the port to 0 in the config) on hosts for various service instances is valuable -- as it avoids having to manually resolve conflicts in configuration management.

This works great already in dropwizard-discovery. However, the admin port is not included in the `InstanceMetadata`, and thus conflicts can still occur when service instances are spun up.

**Comment by jplock** [comment]
This is a good idea.  I'll see if I can make a PR.

**Comment by stantonk** [comment]
I found part of the code where it can get added:

https://github.com/dropwizard/dropwizard-discovery/blob/2c3f45b9a6612515762b0dcec8590f06aa27bff1/src/main/java/io/dropwizard/discovery/core/CuratorAdvertisementListener.java#L36

The other `Connector` is the admin connector, i verified by stepping through in a debugger.

```
@Override
    public void serverStarted(final Server server) {
        // Detect the port Jetty is listening on - works with configured and
        // random port
        for (final Connector connector : server.getConnectors()) {
            if (APPLICATION_CONNECTOR.equals(connector.getName())) {
                final ServerSocketChannel channel = (ServerSocketChannel) connector
                        .getTransport();

                try {
                    final InetSocketAddress socket = (InetSocketAddress) channel
                            .getLocalAddress();
                    advertiser.initListenInfo(socket.getPort());
                    advertiser.registerAvailability();
                    return;
                } catch (final Exception e) {
                    LOGGER.error("Unable to register service in ZK", e);
                }
            }
        }
    }
```

**Comment by jplock** [comment]
@stantonk  Do you have a way to try out my changes in #11 to see if that resolves your issue?

**Comment by stantonk** [comment]
@jplock i do; i won't be able to get to it until probably this weekend though.

I may add a silly hello-world DZ service and a Vagrant file that installs zookeeper and curls the service as some sort of manual integration test if I'm feeling ambitious :)
