### ISSUE TITLE
advertise actual ip address of instance (in adition to listenAddress from config file)

### ISSUE THREAD

**Issue by matej-svetlik** [dropwizard/dropwizard-discovery#16]
If we don't specify _listenAddress_ in config file, dropwizard attempts to autodetect it with warning "_listenAddress not found in configuration file, attempting to auto-detect_". We can specify 0.0.0.0 as _listenAddress_ to suppress this warning (which means listen on every available network interface), but dropwizard then reports 0.0.0.0 to zookeeper. We cannot specify exact address because service runs on multiple hosts.

log:
io.dropwizard.discovery.core.CuratorAdvertiser: Using '**0.0.0.0**' as listenAddress from configuration file
io.dropwizard.discovery.core.CuratorAdvertiser: Registering service (xxx) at **0.0.0.0:2022**

zookeeper node:
{"name":"xxx", "id":"d90b6b6c-43a2-4d33-a402-ae59c9e2610c", "address":"**0.0.0.0**", "port":2022, "sslPort":null, "payload":{"instanceId":"d90b6b6c-43a2-4d33-a402-ae59c9e2610c", "listenAddress":"**0.0.0.0**", "listenPort":2022, "adminPort":3022}, "registrationTimeUTC":1476370415992, "serviceType":"DYNAMIC", "uriSpec":null}

**Comment by kstafford3** [comment]
If I understand this request correctly, it should be possible through custom payloads (#6).
