### ISSUE TITLE
Archive?

### ISSUE THREAD

**Issue by jplock** [dropwizard/dropwizard-discovery#42]
I'm no longer using this library and would like to archive it.  Is there anyone that would like to take over maintenance of it or is using it?

**Comment by joschi** [comment]
I'm all for reducing the side projects we have to maintain. 👍

Maybe you could also ask on the [dropwizard-dev](https://groups.google.com/forum/#!forum/dropwizard-dev) and [dropwizard-user](https://groups.google.com/forum/#!forum/dropwizard-user) mailing lists if someone is interested in taking over maintenance.

**Comment by kstafford3** [comment]
@jplock we're using dropwizard-discovery and I'd be happy to take over maintenance.

**Comment by jplock** [comment]
Thanks @kstafford3, I granted you write access to the repository

**Comment by kstafford3** [comment]
great, thanks!
